kind: ContinuousQuery
apiVersion: v1
name: city-population
spec:
  mode: query
  sources:
    subscriptions:
      - id: geo-db
        nodes:
          - sourceLabel: City
  query: >
    MATCH
      (city:City)
    RETURN
      elementId(city) AS CityId,
      city.name AS Name,
      city.population AS Population,
      city.country_id AS CountryId